### ISSUE TITLE
webpack: Failed to compile.

### ISSUE THREAD

**Issue by irinabov** [negomi/react-tic-tac-toe#3]
Using fedora:latest docker image:
sudo docker run -it fedora:latest bash

dnf update
dnf install nodejs
cd /usr/lib/node_modules/
npm i react-tic-tac-toe
cd react-tic-tac-toe/
npm install
npm start
...
ERROR in ./index.js
Module parse failed: /usr/lib/node_modules/react-tic-tac-toe/index.js Unexpected token (9:16)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (9:16)
    at Parser.pp$4.raise (/usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack/node_modules/acorn/dist/acorn.js:1741:35)
 @ multi main
webpack: Failed to compile.

**Comment by irinabov** [comment]
npm list
/usr/lib
+-- npm@3.10.10
| +-- abbrev@1.0.9 -> /usr/lib/node_modules/npm/node_modules.bundled/abbrev
| +-- ansi-regex@2.0.0 -> /usr/lib/node_modules/npm/node_modules.bundled/ansi-regex
| +-- ansicolors@0.3.2 -> /usr/lib/node_modules/npm/node_modules.bundled/ansicolors
| +-- ansistyles@0.1.3 -> /usr/lib/node_modules/npm/node_modules.bundled/ansistyles
| +-- aproba@1.0.4 -> /usr/lib/node_modules/npm/node_modules.bundled/aproba
| +-- archy@1.0.0 -> /usr/lib/node_modules/npm/node_modules.bundled/archy
| +-- asap@2.0.5 -> /usr/lib/node_modules/npm/node_modules.bundled/asap
| +-- chownr@1.0.1 -> /usr/lib/node_modules/npm/node_modules.bundled/chownr
| +-- cmd-shim@2.0.2 -> /usr/lib/node_modules/npm/node_modules.bundled/cmd-shim
| +-- columnify@1.5.4 -> /usr/lib/node_modules/npm/node_modules.bundled/columnify
| | `-- wcwidth@1.0.0
| |   `-- defaults@1.0.3
| |     `-- clone@1.0.2
| +-- config-chain@1.1.11 -> /usr/lib/node_modules/npm/node_modules.bundled/config-chain
| | `-- proto-list@1.2.4
| +-- debuglog@1.0.1 -> /usr/lib/node_modules/npm/node_modules.bundled/debuglog
| +-- dezalgo@1.0.3 -> /usr/lib/node_modules/npm/node_modules.bundled/dezalgo
| +-- editor@1.0.0 -> /usr/lib/node_modules/npm/node_modules.bundled/editor
| +-- fs-vacuum@1.2.9 -> /usr/lib/node_modules/npm/node_modules.bundled/fs-vacuum
| +-- fs-write-stream-atomic@1.0.8 -> /usr/lib/node_modules/npm/node_modules.bundled/fs-write-stream-atomic
| +-- fstream@1.0.10 -> /usr/lib/node_modules/npm/node_modules.bundled/fstream
| +-- fstream-npm@1.2.0 -> /usr/lib/node_modules/npm/node_modules.bundled/fstream-npm
| | `-- fstream-ignore@1.0.5
| |   `-- minimatch@3.0.3
| |     `-- brace-expansion@1.1.6
| |       +-- balanced-match@0.4.2
| |       `-- concat-map@0.0.1
| +-- glob@7.1.0 -> /usr/lib/node_modules/npm/node_modules.bundled/glob
| | +-- fs.realpath@1.0.0
| | +-- minimatch@3.0.3
| | | `-- brace-expansion@1.1.6
| | |   +-- balanced-match@0.4.2
| | |   `-- concat-map@0.0.1
| | `-- path-is-absolute@1.0.1
| +-- graceful-fs@4.1.9 -> /usr/lib/node_modules/npm/node_modules.bundled/graceful-fs
| +-- has-unicode@2.0.1 -> /usr/lib/node_modules/npm/node_modules.bundled/has-unicode
| +-- hosted-git-info@2.1.5 -> /usr/lib/node_modules/npm/node_modules.bundled/hosted-git-info
| +-- iferr@0.1.5 -> /usr/lib/node_modules/npm/node_modules.bundled/iferr
| +-- imurmurhash@0.1.4 -> /usr/lib/node_modules/npm/node_modules.bundled/imurmurhash
| +-- inflight@1.0.5 -> /usr/lib/node_modules/npm/node_modules.bundled/inflight
| +-- inherits@2.0.3 -> /usr/lib/node_modules/npm/node_modules.bundled/inherits
| +-- ini@1.3.4 -> /usr/lib/node_modules/npm/node_modules.bundled/ini
| +-- init-package-json@1.9.4 -> /usr/lib/node_modules/npm/node_modules.bundled/init-package-json
| | +-- glob@6.0.4
| | | +-- minimatch@3.0.3
| | | | `-- brace-expansion@1.1.6
| | | |   +-- balanced-match@0.4.2
| | | |   `-- concat-map@0.0.1
| | | `-- path-is-absolute@1.0.0
| | `-- promzard@0.3.0
| +-- lockfile@1.0.2 -> /usr/lib/node_modules/npm/node_modules.bundled/lockfile
| +-- lodash._baseindexof@3.1.0 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash._baseindexof
| +-- lodash._baseuniq@4.6.0 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash._baseuniq
| | +-- lodash._createset@4.0.3
| | `-- lodash._root@3.0.1
| +-- lodash._bindcallback@3.0.1 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash._bindcallback
| +-- lodash._cacheindexof@3.0.2 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash._cacheindexof
| +-- lodash._createcache@3.1.2 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash._createcache
| +-- lodash._getnative@3.9.1 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash._getnative
| +-- lodash.clonedeep@4.5.0 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash.clonedeep
| +-- lodash.restparam@3.6.1 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash.restparam
| +-- lodash.union@4.6.0 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash.union
| +-- lodash.uniq@4.5.0 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash.uniq
| +-- lodash.without@4.4.0 -> /usr/lib/node_modules/npm/node_modules.bundled/lodash.without
| +-- mkdirp@0.5.1 -> /usr/lib/node_modules/npm/node_modules.bundled/mkdirp
| | `-- minimist@0.0.8
| +-- node-gyp@3.4.0 -> /usr/lib/node_modules/npm/node_modules.bundled/node-gyp
| | +-- minimatch@3.0.3
| | | `-- brace-expansion@1.1.6
| | |   +-- balanced-match@0.4.2
| | |   `-- concat-map@0.0.1
| | +-- npmlog@3.1.2
| | | +-- are-we-there-yet@1.1.2
| | | | `-- delegates@1.0.0
| | | +-- console-control-strings@1.1.0
| | | +-- gauge@2.6.0
| | | | +-- has-color@0.1.7
| | | | +-- object-assign@4.1.0
| | | | +-- signal-exit@3.0.0
| | | | +-- string-width@1.0.2
| | | | | +-- code-point-at@1.0.0
| | | | | | `-- number-is-nan@1.0.0
| | | | | `-- is-fullwidth-code-point@1.0.0
| | | | |   `-- number-is-nan@1.0.0
| | | | `-- wide-align@1.1.0
| | | `-- set-blocking@2.0.0
| | `-- path-array@1.0.1
| |   `-- array-index@1.0.0
| |     +-- debug@2.2.0
| |     | `-- ms@0.7.1
| |     `-- es6-symbol@3.1.0
| |       +-- d@0.1.1
| |       `-- es5-ext@0.10.12
| |         `-- es6-iterator@2.0.0
| +-- nopt@3.0.6 -> /usr/lib/node_modules/npm/node_modules.bundled/nopt
| +-- normalize-git-url@3.0.2 -> /usr/lib/node_modules/npm/node_modules.bundled/normalize-git-url
| +-- normalize-package-data@2.3.5 -> /usr/lib/node_modules/npm/node_modules.bundled/normalize-package-data
| | `-- is-builtin-module@1.0.0
| |   `-- builtin-modules@1.1.1
| +-- npm-cache-filename@1.0.2 -> /usr/lib/node_modules/npm/node_modules.bundled/npm-cache-filename
| +-- npm-install-checks@3.0.0 -> /usr/lib/node_modules/npm/node_modules.bundled/npm-install-checks
| +-- npm-package-arg@4.2.0 -> /usr/lib/node_modules/npm/node_modules.bundled/npm-package-arg
| +-- npm-registry-client@7.2.1 -> /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client
| | +-- concat-stream@1.5.2
| | | +-- readable-stream@2.0.6
| | | | +-- core-util-is@1.0.2
| | | | +-- isarray@1.0.0
| | | | +-- process-nextick-args@1.0.7
| | | | +-- string_decoder@0.10.31
| | | | `-- util-deprecate@1.0.2
| | | `-- typedarray@0.0.6
| | +-- npmlog@3.1.2
| | | +-- are-we-there-yet@1.1.2
| | | | `-- delegates@1.0.0
| | | +-- console-control-strings@1.1.0
| | | +-- gauge@2.6.0
| | | | +-- has-color@0.1.7
| | | | +-- object-assign@4.1.0
| | | | +-- signal-exit@3.0.0
| | | | +-- string-width@1.0.2
| | | | | +-- code-point-at@1.0.0
| | | | | | `-- number-is-nan@1.0.0
| | | | | `-- is-fullwidth-code-point@1.0.0
| | | | |   `-- number-is-nan@1.0.0
| | | | `-- wide-align@1.1.0
| | | `-- set-blocking@2.0.0
| | `-- retry@0.10.0
| +-- npm-user-validate@0.1.5 -> /usr/lib/node_modules/npm/node_modules.bundled/npm-user-validate
| +-- npmlog@4.0.0 -> /usr/lib/node_modules/npm/node_modules.bundled/npmlog
| | +-- are-we-there-yet@1.1.2
| | | `-- delegates@1.0.0
| | +-- console-control-strings@1.1.0
| | +-- gauge@2.6.0
| | | +-- has-color@0.1.7
| | | +-- object-assign@4.1.0
| | | +-- signal-exit@3.0.0
| | | +-- string-width@1.0.2
| | | | +-- code-point-at@1.0.0
| | | | | `-- number-is-nan@1.0.0
| | | | `-- is-fullwidth-code-point@1.0.0
| | | |   `-- number-is-nan@1.0.0
| | | `-- wide-align@1.1.0
| | `-- set-blocking@2.0.0
| +-- once@1.4.0 -> /usr/lib/node_modules/npm/node_modules.bundled/once
| +-- opener@1.4.2 -> /usr/lib/node_modules/npm/node_modules.bundled/opener
| +-- osenv@0.1.3 -> /usr/lib/node_modules/npm/node_modules.bundled/osenv
| | +-- os-homedir@1.0.1
| | `-- os-tmpdir@1.0.1
| +-- path-is-inside@1.0.2 -> /usr/lib/node_modules/npm/node_modules.bundled/path-is-inside
| +-- read@1.0.7 -> /usr/lib/node_modules/npm/node_modules.bundled/read
| | `-- mute-stream@0.0.5
| +-- read-cmd-shim@1.0.1 -> /usr/lib/node_modules/npm/node_modules.bundled/read-cmd-shim
| +-- read-installed@4.0.3 -> /usr/lib/node_modules/npm/node_modules.bundled/read-installed
| | `-- util-extend@1.0.3
| +-- read-package-json@2.0.4 -> /usr/lib/node_modules/npm/node_modules.bundled/read-package-json
| | +-- glob@6.0.4
| | | +-- minimatch@3.0.3
| | | | `-- brace-expansion@1.1.6
| | | |   +-- balanced-match@0.4.2
| | | |   `-- concat-map@0.0.1
| | | `-- path-is-absolute@1.0.0
| | `-- json-parse-helpfulerror@1.0.3
| |   `-- jju@1.3.0
| +-- read-package-tree@5.1.5 -> /usr/lib/node_modules/npm/node_modules.bundled/read-package-tree
| +-- readable-stream@2.1.5 -> /usr/lib/node_modules/npm/node_modules.bundled/readable-stream
| | +-- buffer-shims@1.0.0
| | +-- core-util-is@1.0.2
| | +-- isarray@1.0.0
| | +-- process-nextick-args@1.0.7
| | +-- string_decoder@0.10.31
| | `-- util-deprecate@1.0.2
| +-- readdir-scoped-modules@1.0.2 -> /usr/lib/node_modules/npm/node_modules.bundled/readdir-scoped-modules
| +-- realize-package-specifier@3.0.3 -> /usr/lib/node_modules/npm/node_modules.bundled/realize-package-specifier
| +-- request@2.75.0 -> /usr/lib/node_modules/npm/node_modules.bundled/request
| | +-- aws-sign2@0.6.0
| | +-- aws4@1.4.1
| | +-- bl@1.1.2
| | | `-- readable-stream@2.0.6
| | |   +-- core-util-is@1.0.2
| | |   +-- isarray@1.0.0
| | |   +-- process-nextick-args@1.0.7
| | |   +-- string_decoder@0.10.31
| | |   `-- util-deprecate@1.0.2
| | +-- caseless@0.11.0
| | +-- combined-stream@1.0.5
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.0
| | +-- forever-agent@0.6.1
| | +-- form-data@2.0.0
| | | `-- asynckit@0.4.0
| | +-- har-validator@2.0.6
| | | +-- chalk@1.1.3
| | | | +-- ansi-styles@2.2.1
| | | | +-- escape-string-regexp@1.0.5
| | | | +-- has-ansi@2.0.0
| | | | `-- supports-color@2.0.0
| | | +-- commander@2.9.0
| | | | `-- graceful-readlink@1.0.1
| | | +-- is-my-json-valid@2.15.0
| | | | +-- generate-function@2.0.0
| | | | +-- generate-object-property@1.2.0
| | | | | `-- is-property@1.0.2
| | | | +-- jsonpointer@4.0.0
| | | | `-- xtend@4.0.1
| | | `-- pinkie-promise@2.0.1
| | |   `-- pinkie@2.0.4
| | +-- hawk@3.1.3
| | | +-- boom@2.10.1
| | | +-- cryptiles@2.0.5
| | | +-- hoek@2.16.3
| | | `-- sntp@1.0.9
| | +-- http-signature@1.1.1
| | | +-- assert-plus@0.2.0
| | | +-- jsprim@1.3.1
| | | | +-- extsprintf@1.0.2
| | | | +-- json-schema@0.2.3
| | | | `-- verror@1.3.6
| | | `-- sshpk@1.10.1
| | |   +-- asn1@0.2.3
| | |   +-- assert-plus@1.0.0
| | |   +-- bcrypt-pbkdf@1.0.0
| | |   +-- dashdash@1.14.0
| | |   +-- ecc-jsbn@0.1.1
| | |   +-- getpass@0.1.6
| | |   +-- jodid25519@1.0.2
| | |   +-- jsbn@0.1.0
| | |   `-- tweetnacl@0.14.3
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- mime-types@2.1.12
| | | `-- mime-db@1.24.0
| | +-- node-uuid@1.4.7
| | +-- oauth-sign@0.8.2
| | +-- qs@6.2.1
| | +-- stringstream@0.0.5
| | +-- tough-cookie@2.3.1
| | `-- tunnel-agent@0.4.3
| +-- retry@0.10.0 -> /usr/lib/node_modules/npm/node_modules.bundled/retry
| +-- rimraf@2.5.4 -> /usr/lib/node_modules/npm/node_modules.bundled/rimraf
| +-- semver@5.3.0 -> /usr/lib/node_modules/npm/node_modules.bundled/semver
| +-- sha@2.0.1 -> /usr/lib/node_modules/npm/node_modules.bundled/sha
| +-- slide@1.1.6 -> /usr/lib/node_modules/npm/node_modules.bundled/slide
| +-- sorted-object@2.0.1 -> /usr/lib/node_modules/npm/node_modules.bundled/sorted-object
| +-- strip-ansi@3.0.1 -> /usr/lib/node_modules/npm/node_modules.bundled/strip-ansi
| +-- tar@2.2.1 -> /usr/lib/node_modules/npm/node_modules.bundled/tar
| | `-- block-stream@0.0.8
| +-- text-table@0.2.0 -> /usr/lib/node_modules/npm/node_modules.bundled/text-table
| +-- uid-number@0.0.6 -> /usr/lib/node_modules/npm/node_modules.bundled/uid-number
| +-- umask@1.1.0 -> /usr/lib/node_modules/npm/node_modules.bundled/umask
| +-- unique-filename@1.1.0 -> /usr/lib/node_modules/npm/node_modules.bundled/unique-filename
| | `-- unique-slug@2.0.0
| +-- unpipe@1.0.0 -> /usr/lib/node_modules/npm/node_modules.bundled/unpipe
| +-- validate-npm-package-license@3.0.1 -> /usr/lib/node_modules/npm/node_modules.bundled/validate-npm-package-license
| | +-- spdx-correct@1.0.2
| | | `-- spdx-license-ids@1.2.0
| | `-- spdx-expression-parse@1.0.2
| |   +-- spdx-exceptions@1.0.4
| |   `-- spdx-license-ids@1.2.0
| +-- validate-npm-package-name@2.2.2 -> /usr/lib/node_modules/npm/node_modules.bundled/validate-npm-package-name
| | `-- builtins@0.0.7
| +-- which@1.2.11 -> /usr/lib/node_modules/npm/node_modules.bundled/which
| | `-- isexe@1.1.2
| +-- wrappy@1.0.2 -> /usr/lib/node_modules/npm/node_modules.bundled/wrappy
| `-- write-file-atomic@1.2.0 -> /usr/lib/node_modules/npm/node_modules.bundled/write-file-atomic
`-- react-tic-tac-toe@1.0.3
  +-- babel@5.8.38 extraneous
  +-- babel-eslint@4.1.8 extraneous
  +-- babel-loader@5.4.2 extraneous
  +-- chai@3.5.0 extraneous
  +-- clean-webpack-plugin@0.1.17 extraneous
  +-- css-loader@0.19.0 extraneous
  +-- eslint@1.10.3 extraneous
  +-- eslint-plugin-react@3.16.1 extraneous
  +-- file-loader@0.8.5 extraneous
  +-- gh-pages@0.4.0 extraneous
  +-- html-webpack-plugin@1.7.0 extraneous
  +-- mocha@2.5.3 extraneous
  +-- mocha-loader@0.7.1 extraneous
  +-- node-sass@3.13.1 extraneous
  +-- normalize.css@3.0.3
  +-- postcss-loader@0.6.0 extraneous
  +-- react@0.14.9
  | +-- envify@3.4.1
  | | +-- jstransform@11.0.3
  | | | +-- base62@1.2.0
  | | | +-- commoner@0.10.8
  | | | | +-- commander@2.11.0
  | | | | +-- detective@4.5.0
  | | | | | +-- acorn@4.0.13
  | | | | | `-- defined@1.0.0
  | | | | +-- glob@5.0.15
  | | | | | +-- inflight@1.0.6
  | | | | | | `-- wrappy@1.0.2
  | | | | | +-- inherits@2.0.3
  | | | | | +-- minimatch@3.0.4
  | | | | | | `-- brace-expansion@1.1.8
  | | | | | |   +-- balanced-match@1.0.0
  | | | | | |   `-- concat-map@0.0.1
  | | | | | +-- once@1.4.0
  | | | | | `-- path-is-absolute@1.0.1
  | | | | +-- graceful-fs@4.1.11
  | | | | +-- iconv-lite@0.4.19
  | | | | +-- mkdirp@0.5.1
  | | | | | `-- minimist@0.0.8
  | | | | +-- private@0.1.8
  | | | | +-- q@1.5.1
  | | | | `-- recast@0.11.23
  | | | |   +-- ast-types@0.9.6
  | | | |   +-- esprima@3.1.3
  | | | |   `-- source-map@0.5.7
  | | | +-- esprima-fb@15001.1.0-dev-harmony-fb
  | | | +-- object-assign@2.1.1
  | | | `-- source-map@0.4.4
  | | |   `-- amdefine@1.0.1
  | | `-- through@2.3.8
  | `-- fbjs@0.6.1
  |   +-- core-js@1.2.7
  |   +-- loose-envify@1.3.1
  |   | `-- js-tokens@3.0.2
  |   +-- promise@7.3.1
  |   | `-- asap@2.0.6
  |   +-- ua-parser-js@0.7.17
  |   `-- whatwg-fetch@0.9.0
  +-- react-addons-test-utils@0.14.8 extraneous
  +-- react-dom@0.14.9
  +-- sass-loader@3.2.3 extraneous
  +-- style-loader@0.12.4 extraneous
  +-- url-loader@0.5.9 extraneous
  +-- webpack@1.15.0 extraneous
  `-- webpack-dev-server@1.16.5 extraneous

npm ERR! extraneous: babel@5.8.38 /usr/lib/node_modules/react-tic-tac-toe/node_modules/babel
npm ERR! extraneous: babel-eslint@4.1.8 /usr/lib/node_modules/react-tic-tac-toe/node_modules/babel-eslint
npm ERR! extraneous: babel-loader@5.4.2 /usr/lib/node_modules/react-tic-tac-toe/node_modules/babel-loader
npm ERR! extraneous: chai@3.5.0 /usr/lib/node_modules/react-tic-tac-toe/node_modules/chai
npm ERR! extraneous: clean-webpack-plugin@0.1.17 /usr/lib/node_modules/react-tic-tac-toe/node_modules/clean-webpack-plugin
npm ERR! extraneous: css-loader@0.19.0 /usr/lib/node_modules/react-tic-tac-toe/node_modules/css-loader
npm ERR! extraneous: eslint@1.10.3 /usr/lib/node_modules/react-tic-tac-toe/node_modules/eslint
npm ERR! extraneous: eslint-plugin-react@3.16.1 /usr/lib/node_modules/react-tic-tac-toe/node_modules/eslint-plugin-react
npm ERR! extraneous: file-loader@0.8.5 /usr/lib/node_modules/react-tic-tac-toe/node_modules/file-loader
npm ERR! extraneous: gh-pages@0.4.0 /usr/lib/node_modules/react-tic-tac-toe/node_modules/gh-pages
npm ERR! extraneous: html-webpack-plugin@1.7.0 /usr/lib/node_modules/react-tic-tac-toe/node_modules/html-webpack-plugin
npm ERR! extraneous: mocha@2.5.3 /usr/lib/node_modules/react-tic-tac-toe/node_modules/mocha
npm ERR! extraneous: mocha-loader@0.7.1 /usr/lib/node_modules/react-tic-tac-toe/node_modules/mocha-loader
npm ERR! extraneous: node-sass@3.13.1 /usr/lib/node_modules/react-tic-tac-toe/node_modules/node-sass
npm ERR! extraneous: postcss-loader@0.6.0 /usr/lib/node_modules/react-tic-tac-toe/node_modules/postcss-loader
npm ERR! extraneous: react-addons-test-utils@0.14.8 /usr/lib/node_modules/react-tic-tac-toe/node_modules/react-addons-test-utils
npm ERR! extraneous: sass-loader@3.2.3 /usr/lib/node_modules/react-tic-tac-toe/node_modules/sass-loader
npm ERR! extraneous: style-loader@0.12.4 /usr/lib/node_modules/react-tic-tac-toe/node_modules/style-loader
npm ERR! extraneous: url-loader@0.5.9 /usr/lib/node_modules/react-tic-tac-toe/node_modules/url-loader
npm ERR! extraneous: webpack@1.15.0 /usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack
npm ERR! extraneous: webpack-dev-server@1.16.5 /usr/lib/node_modules/react-tic-tac-toe/node_modules/webpack-dev-server
[root@617b0e81f8ed node_modules]#

**Comment by irinabov** [comment]
it works if I clone the git instead, closing this issue.
